### ISSUE TITLE
API addScene() error

### ISSUE THREAD

**Issue by MrSandManSy** [farminf/pannellum-react#34]
Excuse me for interrupting you.
When i use 'this.myPannellum.current.getViewer().addScene('secondScene', config);' errors.

Follow is code：
```javascript
  selectOneScene = () => {
    const config = {
      autoLoad: true,
      autoRotate: 6,
      showZoomCtrl: false,
      showControls: false,
      showFullscreenCtrl: false,
      hotSpots: [
        {
          pitch: 10,
          yaw: 130,
          type: 'info',
          text: "struct",
        }
      ],
      basePath: "https://pannellum.org/images/alma.jpg",
    }
    this.myPannellum.current.getViewer().addScene('secondScene', config);
    this.myPannellum.current.getViewer().loadScene('secondScene', 10, 120, 10, true);
  }
```
Follow is api：
![image](https://user-images.githubusercontent.com/28557698/48824822-6e8bb500-eda0-11e8-86f5-fbb9515356cd.png)

Follow is Errors：
![image](https://user-images.githubusercontent.com/28557698/48824386-1bfdc900-ed9f-11e8-9628-1ae5166c75c2.png)

![image](https://user-images.githubusercontent.com/28557698/48824396-24560400-ed9f-11e8-9f19-648cddcd1e5a.png)

**Comment by farminf** [comment]
_unfortunately the tour (which contains scenes) are not supported yet._ 
Actually the main reason is that you can do that with react. Like in the case that you want to go to the other scene you do that with having image define as a state and by changing the image state you change the scene.
or you can define all of your scenes as components and then you can surf between them by routing (/scene1 , /scene2  ....) or having simple **if else** in your render function.
for tour, It needs to be implemented as a separate component because the config file that pannellum accepts is different with the normal panorama.

**Comment by MrSandManSy** [comment]
@farminf Thank you for your suggestion

**Comment by farminf** [comment]
@MrSandManSy welcome :)
