### ISSUE TITLE
Full screen can only be toggled once

### ISSUE THREAD

**Issue by drewgaze** [farminf/pannellum-react#67]
From both my own code and the demo linked from the repository's readme, it appears that full screen can only be toggled once. The first click will enable full screen, pressing escape or clicking the full screen control will minimize but the full screen indicator still shows on the control and clicking it doesn't do anything. This bug doesn't appear to be present in the base pannellum library.

EDIT: I sent a PR to resolve this bug. I am not sure why this library doesn't include Pannellum as a dependency rather than directly including its code into this library.

**Comment by farminf** [comment]
which component? video or image?
what is your browser? can you check if you have an error in the console?
because I just tested it and works both image and video... I tested with chrome on the demo project.

answer to your question: (As far as I remember why I decided to do it in this way at first) because everyone is not just using package managers to include/install the libraries, maybe they use CDN and a link in their HTML file

**Comment by drewgaze** [comment]
I have so far only checked image. This problem only seems to occur on MacOS for some reason, here's the error from the console:

```
Uncaught (in promise) TypeError: Document not active
    at HTMLDivElement.Ae (pannellum.js:2085)
```

**Comment by farminf** [comment]
if it's possible can you provide a gif?
