### ISSUE TITLE
could not be accessed

### ISSUE THREAD

**Issue by yanliwenyong** [farminf/pannellum-react#77]
Hi,

Prompt "could not be accessed" when I load a local website to post an image
File path such as href = "http://192.168.246.35:8199/images/Scan_003.jpg"
I open the url in the browser and can display the image.

thanks!

**Comment by farminf** [comment]
can you elaborate more on this?

**Comment by yanliwenyong** [comment]
Thank you for your reply, I think it should be a cross-domain problem, when my image and my website is not the same address, this problem will appear.

**Comment by Hyllesen** [comment]
I'm getting same issue.... how can you solve this? Shouldn't it be possible to host an image on another domain like AWS S3?

**Comment by mohanyadav** [comment]
> I'm getting same issue, but only on my customers browser (though we are both using Chrome, save version). How can you solve this? Shouldn't it be possible to host an image on another domain like AWS S3?

You have to specify CORS policy on your server on what domains you want your resources to be accessed. My understanding is that this prevents unauthorised domains from accessing your content thus protecting the number of  requests and your resources. 

Imagine a scenario where you upload images to your blog and someone copies the url and uses the URL as is rather than downloading the image and hosting it on their site. Every time someone visits your site - your server resource is utilised. Everytime someone visits their website - your server resource is used. 

Speaking of AWS, you have to specify a CORS policy. They have a detailed page here explaining how to enable CORS - [https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html]()

You can prefer to share it with every domain with an asterisk(*) in the cors rules page
